USE  Superstore;
SELECT FNAME + ' ' + LNAME AS NAME,HIRE_DATE,DATENAME(MONTH,HIRE_DATE)
FROM EMPLOYEES;

SELECT GETDATE()

SELECT DAY(HIRE_DATE) FROM EMPLOYEES;

SELECT FNAME,LNAME FROM EMPLOYEES WHERE LNAME LIKE 'M%';

SELECT NAME FROM COUNTRIES AS C
JOIN CUSTOMERS CU
ON C.COUNTRY_ID = CU.COUNTRY_ID
UNION
SELECT C.FNAME FROM COUNTRIES AS C
JOIN DEPARTMENTS AS D
ON C.COUNTRY_ID = D.COUNTRY_ID
--2
SELECT O.ORDER_ID, O.ORDER_DATE,SUM(UNIT_PRICE) AS TOTAL 
FROM ORDERS AS O
JOIN ORDER_ITEMS AS OI ON O.ORDER_ID = OI.ORDER_ID
WHERE YEAR(ORDER_DATE) = 2000
GROUP BY O.ORDER_ID,ORDER_DATE
--3
SELECT O.ORDER_ID, O.ORDER_DATE,SUM(UNIT_PRICE) AS TOTAL,
DATEADD(DAY,7,ORDER_DATE) AS DATE_PAY
FROM ORDERS AS O
JOIN ORDER_ITEMS AS OI ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.ORDER_ID,ORDER_DATE
--4
SELECT E.FNAME + ' ' +E.LNAME,COUNT(O.ORDER_ID) 
FROM EMPLOYEES AS e
LEFT JOIN ORDERS AS O
ON e.EMPLOYEE_ID = O.EMPLOYEE_ID
GROUP BY(E.FNAME + ' ' +E.LNAME)

--5
SELECT E.FNAME
FROM EMPLOYEES AS e
INTERSECT
SELECT FNAME FROM CUSTOMERS

--6
SELECT FNAME
FROM EMPLOYEES 
WHERE FNAME IN (SELECT FNAME FROM CUSTOMERS)


--7
SELECT DISTINCT FNAME FROM EMPLOYEES 
WHERE FNAME IN (SELECT FNAME FROM CUSTOMERS)


--7
SELECT DISTINCT FNAME FROM EMPLOYEES AS E
WHERE EXISTS (SELECT * FROM CUSTOMERS AS C WHERE E.FNAME=C.FNAME)
SELECT DISTINCT E.FNAME FROM EMPLOYEES AS E
JOIN CUSTOMERS AS C
ON C.FNAME = E.FNAME

--9

SELECT  FNAME FROM EMPLOYEES
EXCEPT 
SELECT FNAME FROM CUSTOMERS

SELECT DISTINCT FNAME FROM EMPLOYEES
WHERE FNAME NOT IN(SELECT FNAME FROM CUSTOMERS)


SELECT DISTINCT FNAME FROM EMPLOYEES
WHERE FNAME <> ALL(SELECT FNAME FROM CUSTOMERS)

--10

SELECT DISTINCT C.NAME FROM COUNTRIES AS C
JOIN CUSTOMERS AS CU
ON C.COUNTRY_ID = CU.COUNTRY_ID
LEFT JOIN DEPARTMENTS AS D
ON C.COUNTRY_ID = D.COUNTRY_ID
WHERE D.COUNTRY_ID IS NULL

--11

SELECT FNAME + ' ' + LNAME AS FULL_NAME, HIRE_DATE FROM EMPLOYEES AS E
WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE) FROM EMPLOYEES)

SELECT TOP 2 WITH TIES FNAME + ' ' LNAME ,HIRE_DATE 
FROM EMPLOYEES 
ORDER BY HIRE_DATE DESC

--12
SELECT TOP 1 WITH TIES FNAME + ' ' + LNAME AS NAME, SUM(UNIT_PRICE*QUANTITY) AS TOTAL
FROM CUSTOMERS C JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY FNAME + ' ' + LNAME
ORDER BY TOTAL


--14
SELECT E.FNAME, E.SALARY
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY > (
    SELECT AVG(E1.SALARY)
    FROM EMPLOYEES E1
    WHERE E1.DEPARTMENT_ID = E.DEPARTMENT_ID
)

--15

SELECT TOP 3 NAME ,AVG(UNIT_PRICE * QUANTITY) AS TOTAL
FROM PRODUCTS AS P 
JOIN ORDER_ITEMS AS ot
ON P.PRODUCT_ID = ot.PRODUCT_ID
GROUP BY P.NAME

---16

SELECT AVG(COUNT_ORDER) AS AVERAGE_ORDERS 
FROM(
SELECT EMP.FNAME, COUNT(O.ORDER_ID) AS COUNT_ORDER FROM EMPLOYEES AS EMP
JOIN ORDERS AS O 
ON EMP.EMPLOYEE_ID = O.EMPLOYEE_ID
JOIN DEPARTMENTS AS d
ON EMP.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID = 80
GROUP BY EMP.FNAME) AS SUBQUERY

