

--6.1
CREATE VIEW Employee_SALARY AS
SELECT FNAME,LNAME,SALARY/12 AS EMPLOYEE_MONTH_SALARY,DEPARTMENT_ID FROM EMPLOYEES AS EMPL

SELECT * FROM Employee_SALARY



--6.2
CREATE VIEW MANAGER_VIEW AS
SELECT EMP.FNAME + ' '+ EMP.LNAME AS FULL_NAME ,SUM(UNIT_PRICE*QUANTITY) AS total
FROM ORDERS AS O
JOIN ORDER_ITEMS AS OI
ON O.ORDER_ID = OI.ORDER_ID
JOIN EMPLOYEES AS EMP
ON EMP.EMPLOYEE_ID = O.EMPLOYEE_ID
JOIN EMPLOYEES AS EMP_M
ON EMP_M.MANAGER_ID = EMP.MANAGER_ID
GROUP BY  EMP.FNAME + ' '+ EMP.LNAME

SELECT * FROM MANAGER_VIEW

--6.3

SELECT JOB_TITLE, MIN(EMPL.HIRE_DATE) AS MIN_HIREDATE,MAX(EMPL.HIRE_DATE) AS MAX_HIREDATE FROM JOBS AS J
JOIN EMPLOYEES AS EMPL
ON J.JOB_ID = EMPL.JOB_ID
GROUP BY(JOB_TITLE)
